# Generated by Django 5.0.2 on 2024-03-04 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=225, null=True)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'build_materials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('middlename', models.CharField(blank=True, max_length=100, null=True)),
                ('numberphone', models.CharField(max_length=11, unique=True)),
                ('useremail', models.CharField(max_length=25, unique=True)),
                ('birthday', models.DateField(unique=True)),
                ('password', models.CharField(max_length=15)),
                ('post', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=225, null=True)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=100)),
                ('numberphone', models.CharField(max_length=11, unique=True)),
                ('useremail', models.CharField(max_length=25, unique=True)),
                ('birthday', models.DateField()),
                ('address_of_the_building', models.CharField(max_length=30, unique=True)),
                ('fk_materials', models.ForeignKey(db_column='fk_materials', on_delete=django.db.models.deletion.DO_NOTHING, to='WebBulder.buildmaterials')),
                ('fk_employee', models.ForeignKey(db_column='fk_employee', on_delete=django.db.models.deletion.DO_NOTHING, to='WebBulder.employee')),
                ('fk_service', models.ForeignKey(db_column='fk_service', on_delete=django.db.models.deletion.DO_NOTHING, to='WebBulder.service')),
            ],
            options={
                'db_table': 'costumer',
            },
        ),
        migrations.CreateModel(
            name='SpeshalCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=225, null=True)),
                ('type_car', models.CharField(max_length=15)),
                ('fk_employee', models.ForeignKey(db_column='fk_employee', on_delete=django.db.models.deletion.DO_NOTHING, to='WebBulder.employee')),
            ],
            options={
                'db_table': 'speshal_car',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='fk_speshal_car',
            field=models.ForeignKey(db_column='fk_speshal_car', on_delete=django.db.models.deletion.DO_NOTHING, to='WebBulder.speshalcar'),
        ),
    ]
