# Generated by Django 5.0.2 on 2024-03-05 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebBulder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildmaterials',
            options={},
        ),
    ]
